server:
  port: 10086

spring:
  application:
    name: klei-gateway0

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.2:10087/eureka
    register-with-eureka: false
    fetch-registry: false