server:
  port: 10010

spring:
  application:
    name: klei-gateway

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.2:10087/eureka
      registry-fetch-interval-seconds: 5


zuul:
  prefix: /api